version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_note_taking_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: