# Generated by Django 4.2.4 on 2023-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, help_text="Username should include only latin letters, digits and dots.         Username can't start and end with a dot or don't contain letters.         Digits can be added only at the end.", max_length=150, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, help_text='Your name appear around NoteD where you post or do actions.', max_length=50, verbose_name='Full Name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_active', models.BooleanField(default=True, verbose_name='User activated')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(related_name='accounts_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='accounts_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
